filebeat.prospectors:

- input_type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /home/erwann/matinale_es/log-generator/target/shop*.log
  document_type: shop

- input_type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /home/erwann/matinale_es/log-generator/target/application*.log
  document_type: application

  ### Multiline options
  multiline.pattern: ^2017
  multiline.negate: true
  multiline.match: after

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]
