#=========================== Filebeat prospectors =============================

filebeat.prospectors:

# Each - is a prospector. Most options can be set at the prospector level, so
# you can use different prospectors for various configurations.
# Below are the prospector specific configurations.

- input_type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /home/erwann/matinale_es/log-generator/target/shop*.log
  document_type: shop
  pipeline: "pipeline-shop" 


- input_type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /home/erwann/matinale_es/log-generator/target/application*.log
  document_type: application
  pipeline: "pipeline-application" 


#================================ Outputs =====================================

# Configure what outputs to use when sending the data collected by the beat.
# Multiple outputs may be used.

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]
  index: sales-%{+YYYY.MM.dd}


